version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mcwiseman97-umbrel-app-store-fittrack_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/mcwiseman97/fittrack:1.0.4@sha256:f2bd55a3d886f266c8a5fd7a1558deaec415cc8efa3f3b91f5383d118d6c4f1c
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      DATABASE_URL: /data/fittrack.db
      NODE_ENV: production
