version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mcwiseman97-umbrel-app-store-fittrack_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/mcwiseman97/fittrack:1.0.2@sha256:31c54b9d96d3edf28e2dd42f0a9d96a3369b4e3e757dd4d60e5a243e4e0de606
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      DATABASE_URL: /data/fittrack.db
      NODE_ENV: production
