version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mcwiseman97-umbrel-app-store-fittrack_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/mcwiseman97/fittrack:1.2.5@sha256:2f72671adb7e34ed01bbf29823a39f60bd75ee2aaa6d5d8650ba1fbf503e21f1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      DATABASE_URL: /data/fittrack.db
      NODE_ENV: production
      TZ: America/Chicago
